version: 0.0
os: linux
files:
  - source: ./html5-canvas-drawing-app.html
    destination: var/www/html
hooks:
  BeforeInstall:
    -  location: scripts/start_server
       timeout: 300s
       runas: root
  ApplicationStop:
    - location: scrtpts/after_install
      timout: 300s
      runas: root
